//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConectarDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ticket
    {
        public int ticket_id { get; set; }
        public int fila_id { get; set; }
        public int compra_id { get; set; }
        public int num_asiento { get; set; }
    
        public virtual fila fila { get; set; }
        public virtual compra compra { get; set; }
    }
}
