
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ConectarDatos
{

using System;
    using System.Collections.Generic;
    
public partial class ticket
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ticket()
    {

        this.compra = new HashSet<compra>();

    }


    public int ticket_id { get; set; }

    public int fila_id { get; set; }

    public int compra_id { get; set; }

    public int num_asiento { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<compra> compra { get; set; }

    public virtual fila fila { get; set; }

}

}
